### ISSUE TITLE
Indexing jank that needs resolution

### ISSUE THREAD

**Issue by jeffdoms** [satsnames/satsnamesapi#1]
I'm coping these problems from a discussion thread on discord. I agree this stuff needs to be resolved in the spec and then updated in the indexer. 

--

> In this case the docs don't say anything about content type of inscriptions and the official API only parses text/plain types. Unisat also parses application/json, maybe even all text formats. But using application/json for JSON is pretty logical. 
> 
> 1. Some inscriptions has application/json content type and many indexers only parse text/plain
> 
> 2. What about invalid JSON? Trailing comma, different kind of quotation marks, new line (\n) inside a quite, etc
> 
> 3. Case sensitivity is not that simple too. Should an app to convert a name to lower case or request the name as is. It needs to be clarified

--

> "1. Validate that the inscription's content type includes text/plain"
> 
> Well, it does say
> 
> So the intent principle has been included too
> 
> "the goal of validating is to be permissive of any clear and parsable intent to register a single .sats name"
> 
> Therefore application/json needs to be recognized

--

> Has anybody seen inscriptions like this?
> { "name": "satoshi.sats
> " }
> 
> Note sure, but I think I've seen some
> 
> Not valid JSON
> 
> A new line inside a quote
> 

--

> The problem with the intent principle is, there can be tons of mistakes we don't know about yet. People could miss a comma, for example. So if we really count any intent to register a .sats name, there needs to be a general algorithm that searches for a name 
> 
> As I said a few times before, it could be like that:
> 
> 1. Search for the first occurrence of ".sats"
> 2. Parse the entire name
> 3. Remove any parts of invalid JSON syntax like quotes 
> 
> --
> 
> Say we've got an inscription like this
> 
> {
>  "p":"sns"
>  "op":"reg"
>  "name":"satoshi.sats"
> }
> 
> Commas are missed, so it's invalid JSON
> 
> 1. We search for ".sats"
> 2. Parse the entire name: "name":"satoshi.sats (since there are no spaces)
> 3. Remove any parts of invalid syntax: "name":" 
> 
> The next problem is someone might really want names like "satoshi.sats
> 
> So first we need to recognize it's invalid json like it starts with { or something like that
>

**Comment by sats-wizard** [comment]
Thanks for providing these detailed cases. I always knew that getting this right would take a few iterations. Apologies I didn't expect entire marketplaces to spring up before the standard was stabilized. This is great feedback. Please keep it coming. 

I think we have a mix of oversights on our part, clarifications needed in the documentation, and maybe misunderstandings. I am committed to making the specification solid and I want more feedback on every detail until it is perfect.

Here is what I would propose in terms of changes to both the protocol and all indexers:

- Include `application/json` and `text/plain`.
- JSON5 is valid and we should strictly validate it. There should be no exceptions. If we go down that road, it will lead to too many exceptions and a bad standard. The change here would be to get rid of the exception for funky quotes. By the way, JSON values that contain `\n` should already be failing. 
- For non-JSON, "first is first" should be more permissive. We can clean up spaces and newlines as we already are.
- Case sensitivity: The convention we are using is to convert all characters to lowercase and convert all queries to lowercase. I think this covers it, but let me know if otherwise.

I think these tweaks would cover all the problems spelled out above and also reduce the complexity burden for all indexers. If this covers it I can start making changes.

What is still missing? Thanks again for sharing feedback.

**Comment by jdr377** [comment]
does https://api.sats.id/ already return json registrations?

substituting quotation marks seems reasonable due to international keyboards potentially causing this problem.

other than that - if there are missing quotation marks or brackets missing then it should probably be deemed a failure to register.

some people aren't going to be happy but keeping the parser conditions simple and sensible sounds better than trying to cover every potential case of failure and finding any excuse to prevent ownership to registrants that formatted correctly.

**Comment by hamslice3000** [comment]
> Thanks for providing these detailed cases. I always knew that getting this right would take a few iterations. Apologies I didn't expect entire marketplaces to spring up before the standard was stabilized. This is great feedback. Please keep it coming.
> 
> I think we have a mix of oversights on our part, clarifications needed in the documentation, and maybe misunderstandings. I am committed to making the specification solid and I want more feedback on every detail until it is perfect.
> 
> Here is what I would propose in terms of changes to both the protocol and all indexers:
> 
> * Include `application/json` and `text/plain`.
> * JSON5 is valid and we should strictly validate it. There should be no exceptions. If we start making exceptions (as the examples imply we should), it will lead to too much complexity and a bad standard. The change here would be to get rid of the exception for funky quotes. By the way, JSON values that contain `\n` should already be failing.
> * For non-JSON, "first is first" should be more permissive. We can clean up spaces and newlines as we already are.
> * Case sensitivity: The convention we are using is to convert all characters to lowercase and convert all queries to lowercase. I think this covers it, but let me know if otherwise.
> 
> I think these tweaks would cover all the problems spelled out above and also reduce the complexity burden for all indexers. If this covers it I can start making changes.
> 
> What is still missing? Thanks again for sharing feedback.

Yes, thanks for the communication. When you say no exceptions for incorrect JSON, that ignores the fact that the original example on the docs and first .sats JSON was incorrect (trailing comma), and many followed this, including me.

I have since been told by Name_Sats this is ok.

Also boosting that case, if there is a .sats in the invalid JSON, that should be extracted, as per the intentions published on the docs saying, and I paraphrase "any .sats in an inscription" are counted (except of course if they inscribe 100s in 1 inscription, the first in list only is counted).

Finally , there are emojis and text/numbers with hidden characters. This is a tricky area, and needs some further consideration. it can lead to some seeming duplicates, so I'm open to what happens to them, even though I have a few accidentally done, I could see the case for excluding them....

**Comment by sats-wizard** [comment]
Thanks for all the feedback. I made a few changes to both the docs and our indexer that should cover all concerns above. Please check it out and share feedback: https://docs.sats.id/sats-names/protocol-spec
